import "./globals.css"
import type { Metadata } from "next"
import { Sora } from "next/font/google"
import Header from "@/components/header"

const sora = Sora({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <Header />
        <main className="flex flex-col min-h-screen w-full">{children}</main>
      </body>
    </html>
  )
}
